dataframe:
  - dask/dataframe/*
  - dask/dataframe/**/*

array:
  - dask/array/*
  - dask/array/**/*

io:
  - dask/dataframe/io/*
  - dask/dataframe/io/**/*

documentation:
  - dask/docs/*
  - dask/docs/**/*
