"Area:Dataframe":
  - dask/dataframe/*
  - dask/dataframe/**/*

"Area:Array":
  - dask/array/*
  - dask/array/**/*

"Area:IO":
  - dask/dataframe/io/*
  - dask/dataframe/io/**/*

"Area:Documentation":
  - dask/docs/*
  - dask/docs/**/*

"Area:Dispatch":
  - dask/array/backends.py
  - dask/array/dispatch.py
  - dask/dataframe/backends.py
  - dask/dataframe/dispatch.py
  - dask/dataframe/extensions.py