repos:
  -   repo: https://github.com/pycqa/isort
      rev: 5.9.3
      hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  -   repo: https://github.com/psf/black
      rev: 21.9b0
      hooks:
      - id: black
        language_version: python3
        exclude: versioneer.py
        args:
          - --target-version=py37
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        additional_dependencies:
          # Type stubs
          - types-docutils
          - types-pkg_resources
          - types-PyYAML
          - types-requests
          - types-setuptools
          # Libraries exclusively imported under `if TYPE_CHECKING:`
          - typing_extensions  # To be reviewed after dropping Python 3.7
          # Typed libraries
          - numpy
