repos:
-   repo: https://github.com/python/black
    rev: 73bd7038fbefdb1c6a61fa1edf16ff61613050a5
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
