language: python
sudo: false
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"


install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytest numpy into pip coverage toolz pandas cython
  - conda install -c blaze blaze
  - pip install coveralls dill --use-mirrors
  - pip install git+https://github.com/ContinuumIO/chest
  - pip install git+https://github.com/blosc/bcolz --upgrade

  # Install dask
  - python setup.py install

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then py.test --doctest-modules dask --verbose; else py.test dask --verbose; fi
    - py.test pframe --doctest-modules --verbose

after_success:
    - coveralls

notifications:
  email: false
