language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

addons:
    apt:
        packages:
        - graphviz
        - liblzma-dev

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install numpy scipy pandas pytables h5py bcolz pytest coverage toolz scikit-learn cytoolz chest blosc cython psutil ipython
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then conda install distributed cloudpickle bokeh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install backports.lzma; fi
  - pip install git+https://github.com/mrocklin/partd --upgrade
  - pip install git+https://github.com/mrocklin/cachey --upgrade
  - pip install blosc --upgrade
  - pip install graphviz moto
  - if [[ $TRAVIS_PYTHON_VERSION < '3' ]]; then pip install git+https://github.com/Blosc/castra; fi

  # Install dask
  - pip install -e .[complete]

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run $(which py.test) dask --runslow --doctest-modules --verbose; else py.test dask --verbose; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage report --show-missing; pip install coveralls ; coveralls ; fi

notifications:
  email: false
