[build-system]
requires = ["hatchling>=1.13.0", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "dask"
description = "Parallel PyData with Task Scheduling"
readme = "README.rst"
license = {text = "BSD-3-Clause"}
requires-python = ">=3.8"
maintainers = [
    { name = "Matthew Rocklin", email = "mrocklin@gmail.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "Topic :: System :: Distributed Computing",
]
dependencies = [
    "click >= 7.0",
    "cloudpickle >= 1.1.1",
    "fsspec >= 0.6.0",
    "packaging >= 20.0",
    "partd >= 1.2.0",
    "pyyaml >= 5.3.1",
    "toolz >= 0.8.2",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://dask.org/"
Tracker = "https://github.com/dask/dask/issues"

[project.optional-dependencies]
array = [
    "numpy >= 1.21",
]
bag = []
dataframe = [
    "numpy >= 1.21",
    "pandas >= 1.3",
]
distributed = [
    "distributed == 2023.3.1",
]
diagnostics = [
    "bokeh >= 2.4.2, < 3",
    "jinja2 >= 2.10.3",
]
delayed = []
complete = [
    "numpy >= 1.21",
    "pandas >= 1.3",
    "distributed == 2023.3.1",
    "bokeh >= 2.4.2, < 3",
    "jinja2 >= 2.10.3",
    "pyarrow >= 7.0",
    "lz4 >= 4.3.2",
]
test = [
    "pandas[test]",
    "pytest",
    "pytest-rerunfailures",
    "pytest-xdist",
    "pre-commit",
]

[project.scripts]
dask = "dask.__main__:main"

[project.entry-points."dask.array.backends"]
cupy = "dask.array.cupy_entry_point:CupyBackendEntrypoint"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "dask/_version.py"

[tool.hatch.build.targets.sdist]
include = ["/dask"]

[tool.isort]
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "DISTRIBUTED",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
profile = "black"
skip_gitignore = "true"
force_to_top = "true"
default_section = "THIRDPARTY"
known_first_party = ["dask"]
known_distributed = ["distributed"]

[tool.mypy]
# Silence errors about Python 3.9-style delayed type annotations on Python 3.8
python_version = "3.9"
# See https://github.com/python/mypy/issues/12286 for automatic multi-platform support
platform = "linux"
# platform = win32
# platform = darwin
plugins = ["numpy.typing.mypy_plugin"]
allow_untyped_decorators = false
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true

[tool.codespell]
ignore-words-list = ["coo", "nd"]
skip = "docs/source/changelog.rst"

[tool.pytest.ini_options]
addopts = ["-v", "-rsxfE", "--durations=10", "--color=yes"]
xfail_strict = true
markers = [
    "network: Test requires an internet connection",
    "slow: Skipped unless --runslow passed",
    "gpu: marks tests we want to run on GPUs",
    "skip_with_pyarrow_strings: Tests that should be skipped when pyarrow string conversion is turned on",
    "xfail_with_pyarrow_strings: Tests that should be xfailed when pyarrow string conversion is turned on",
]
filterwarnings = [
    # From Cython-1753
    "ignore:can't resolve:ImportWarning",
    "error:::dask[.*]",
    "error:::pandas[.*]",
    "error:::numpy[.*]",
    "error:::distributed[.*]",
    # From https://github.com/numpy/numpy/issues/20225
    "ignore:The distutils.sysconfig module is deprecated, use sysconfig instead:DeprecationWarning:numpy",
    # With no network access, distributed raises a warning when detecting local IP address
    "ignore:Couldn't detect a suitable IP address:RuntimeWarning:distributed",
    # Ignore FutureWarning for change in group_keys behavior: no changes required on the dask side.
    # https://pandas.pydata.org/docs/dev/whatsnew/v1.5.0.html#using-group-keys-with-transformers-in-groupby-apply
    "ignore:Not prepending group keys:FutureWarning",
    "ignore:.*:dask.tests.warning_aliases.RemovedIn20Warning",
]


[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
]
ignore_errors = true


[tool.coverage.run]
omit = [
    "*/test_*.py",
    "dask/_version.py",
]
source = ["dask/"]
