name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - packaging=20.0
  - python=3.9
  - pyyaml=5.3.1
  - click=8.0
  - cloudpickle=1.5.0
  - partd=1.2.0
  - fsspec=2021.09.0
  - importlib-metadata=4.13.0
  - toolz=0.10.0
  # optional dependencies pulled in by pip install dask[distributed]
  - pip
  - pip:
      - git+https://github.com/dask/distributed@03ea2e1cfe42427fc753c3fb828d2fd2d7b1e9d7
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
