# This job includes coverage
name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.9
  - numpy
  - pandas
  # test dependencies
  - pytest
  - pytest-cov
  - pytest-xdist
  - moto
  - flask
  # Not available for Python 3.9 on conda-forge yet
  # - fastparquet
  - h5py
  - pytables
  - zarr
  - tiledb-py
  - fsspec
  - sqlalchemy
  - pyarrow
  - coverage
  - jsonschema
  # other -- IO
  # Not available for Python 3.9 on conda-forge yet
  # - bcolz
  - blosc
  - boto3
  - botocore
  - bokeh
  - httpretty
  - aiohttp
  - chest
  - s3fs
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - graphviz
  - ipython
  - lz4
  # Not available for Python 3.9 on conda-forge yet
  # - numba
  - partd
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - toolz
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - pandas-datareader
  - python-xxhash
  - mmh3
  - pip
  - pip:
    # TEMP HACK DO NOT MERGE!
    # - git+https://github.com/dask/distributed
    - git+https://github.com/crusaderky/distributed.git@python39
