# This job includes coverage
name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.9.*
  - numpy=1.20.*
  - pandas=1.2.*
  # test dependencies
  - pytest
  - pytest-xdist
  - moto>=1.3.14
  - flask
  # Note available for Python 3.9 on conda-forge yet
  # - fastparquet
  - h5py
  - pytables
  - zarr
  - tiledb-py
  - fsspec>=0.6.0
  - sqlalchemy
  - pyarrow>=0.14.0
  - coverage
  - jsonschema
  # other -- IO
  # Note available for Python 3.9 on conda-forge yet
  # - bcolz
  - blosc
  - boto3
  - botocore
  - bokeh
  - httpretty
  - aiohttp
  - chest
  - s3fs
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - graphviz
  - ipython
  - lz4
  # Note available for Python 3.9 on conda-forge yet
  # - numba
  - partd
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - toolz
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - pandas-datareader
  - python-xxhash
  - mmh3
  - pip
