name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.6.*
  - numpy=1.15.*
  - pandas=0.25.*
  # test dependencies
  - pytest
  - pytest-xdist
  - moto>=1.3.14
  - flask
  - coverage
  - jsonschema
  # Issue with conda package for NumPy 1.15?
  # See fastparquet-444
  # - fastparquet
  - h5py
  - pytables
  - fsspec>=0.7.4
  - zarr
  - tiledb-py
  - sqlalchemy
  - pyarrow=0.14.*
  # other -- IO
  - bcolz
  - blosc
  - s3fs=0.4
  - boto3
  - botocore
  - aiohttp
  - bokeh
  - httpretty
  - chest
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - graphviz=2.42.3  # pinned to avoid https://github.com/dask/dask/issues/7231
  - ipython
  - lz4
  - numba
  - partd
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - toolz
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - pandas-datareader
  - python-xxhash
  - mmh3
  - pip
