# This job tests against upstream dev
name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.8.*
  # For the dependencies. These will be re-installed later.
  - numpy
  - pandas
  # test dependencies
  - pytest
  - pytest-xdist
  - moto>=1.3.14
  - flask
  - fastparquet
  - h5py
  - pytables
  - zarr
  - tiledb-py
  - sqlalchemy
  - pyarrow>=0.14.0,!=2.0.0
  - jsonschema
  # other -- IO
  - bcolz
  - blosc
  - s3fs
  - fsspec>=0.6.0
  - boto3
  - botocore
  - aiohttp
  - bokeh
  - httpretty
  - chest
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - graphviz
  - ipython
  - lz4
  - numba>=0.49
  - partd
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - toolz
  - python-snappy
  - cachey
  # TODO: python-graphviz 0.16 is broken on windows so we're pinning to
  # 0.15 as a temporary workaround. Remove pinning once
  # https://github.com/conda-forge/python-graphviz-feedstock/issues/42 is resolved
  - python-graphviz=0.15
  - python-xxhash
  - mmh3
  - pip
