# This job includes coverage
name: test-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  # required dependencies
  - python=3.8
  - packaging
  - numpy=1.21
  - pandas=1.3
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
  - moto
  - flask
  - fastparquet
  - h5py
  - pytables
  - zarr
  # `tiledb-py=0.17.5` lead to strange seg faults in CI.
  # We should unpin when possible.
  # https://github.com/dask/dask/pull/9569
  - tiledb-py<0.17.4
  - pyspark
  - tiledb>=2.5.0
  - xarray
  - fsspec
  # Pin until sqlalchemy 2 support is added https://github.com/dask/dask/issues/9896
  - sqlalchemy>=1.4.0,<2
  - pyarrow=7
  - coverage
  - jsonschema
  # other -- IO
  - boto3
  - botocore
  # Temporary restriction until https://github.com/dask/distributed/issues/7173 is resolved
  - bokeh<3
  - httpretty
  - aiohttp
  # Need recent version of s3fs to support newer aiobotocore versions
  # https://github.com/dask/s3fs/issues/514
  - s3fs>=2021.8.0
  - click
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - importlib-metadata>=4.13.0
  - ipython
  - ipycytoscape
  - lz4
  - numba
  - partd
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - toolz
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - python-xxhash
  - mmh3
  - jinja2
  - pip
  - pip:
      - git+https://github.com/dask/distributed
