name: CI Additional

on: [push, pull_request]

jobs:
  mindeps:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, 'test-mindeps') || github.event_name != 'pull_request'"

    strategy:
      matrix:
        environment: ["mindeps-array-dataframe", "mindeps-bag-delayed"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1.7.0
        with:
          miniconda-version: "latest"
          python-version: 3.8
          environment-file: continuous_integration/environment-${{ matrix.environment }}.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        shell: bash -l {0}
        env:
          UPSTREAM_DEV: 1
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: source continuous_integration/scripts/run_tests.sh

  hdfs:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, 'test-hdfs') || github.event_name != 'pull_request'"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Start HDFS
        shell: bash -l {0}
        run: source continuous_integration/hdfs/startup_hdfs.sh

      - name: Install
        shell: bash -l {0}
        run: source continuous_integration/hdfs/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: source continuous_integration/hdfs/run_tests.sh
