name: Upstream

on:
  schedule:
    - cron: "0 1 * * *"
  push:
  pull_request:

jobs:

  check:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    outputs:
      test-upstream: ${{ steps.detect-trigger.outputs.trigger-found }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: xarray-contrib/ci-trigger@v1
        id: detect-trigger
        with:
          keyword: "test-upstream"

  build:
    needs: check
    runs-on: ubuntu-latest
    if: |
      needs.check.outputs.test-upstream == 'true'
      || (github.repository == 'dask/dask' && github.event_name != 'pull_request')

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        # Latest commit as of 2021-02-07
        # TODO replace with label as soon as it's available
        uses: conda-incubator/setup-miniconda@77b16ed746da28724c61e1f1ad23395a4b695ef5
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: "3.8"
          environment-file: continuous_integration/environment-3.8-dev.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        shell: bash -l {0}
        env:
          UPSTREAM_DEV: 1
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: source continuous_integration/scripts/run_tests.sh
