name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  checks:
    name: Documentation build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: get commit message
      run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Dask
      if: "!contains(env.commitmsg , '[ci skip]')"
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .

    - name: Install doc dependencies
      if: "!contains(env.commitmsg , '[ci skip]')"
      run: python -m pip install -r docs/requirements-docs.txt

    - name: Build docs
      if: "!contains(env.commitmsg , '[ci skip]')"
      run: |
        cd docs
        make html
