name: "Issue and PR Labeler"
on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened, reopened]
jobs:
  label-all-on-open:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@main
        with:
          add-labels: "needs triage"
          ignore-if-labeled: false
